Specify rust-version and remove outdated info from README
The workspace does not compile with Rust 1.60.0 due to a neon target feature:

```log
error[E0658]: the target feature `neon` is currently unstable
  --> src/simd/aarch64.rs:11:18
   |
11 | #[target_feature(enable = "neon")]
   |                  ^^^^^^^^^^^^^^^
   |
   = note: see issue #44839 <https://github.com/rust-lang/rust/issues/44839> for more information
```